# Generated by Django 2.0.6 on 2018-09-12 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_banda', models.CharField(max_length=100)),
                ('numero_integrantes', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='banda')),
            ],
        ),
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='Masculino', max_length=12)),
                ('direccion', models.TextField(max_length=30)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='integrante')),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandas.Banda')),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_nacionalidad', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=100)),
                ('edad', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='integrante',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, to='bandas.Rol'),
        ),
        migrations.AddField(
            model_name='banda',
            name='nacionalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandas.Nacionalidad'),
        ),
    ]
